-- 최댓값 구하기
SELECT MAX(DATETIME) AS 시간 FROM ANIMAL_INS; 

-- 최솟값 구하기
SELECT MIN(DATETIME) AS 시간 FROM ANIMAL_INS;

-- 동물 수 구하기
SELECT COUNT(*) AS count FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS WHERE NAME IS NOT NULL;
SELECT COUNT(*) AS count FROM (SELECT DISTINCT NAME FROM ANIMAL_INS WHERE NAME IS NOT NULL) A;

-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS MAX_PRICE FROM PRODUCT;

-- 가격이 제일 비싼 식품의 정보 출력하기
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);