-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 카테고리 별 상품 개수 구하기
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY;

-- 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, 
       If(INSTR(SEX_UPON_INTAKE, 'Neutered')>0 OR INSTR(SEX_UPON_INTAKE, 'Spayed')>0, 'O', 'X') AS 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INSTR(NAME, 'el')>0 AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME;

-- 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID;

-- 오랜 기간 보호한 동물(2)
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(SECOND, ANIMAL_INS.DATETIME, ANIMAL_OUTS.DATETIME) DESC
LIMIT 2;

-- 조건별로 분류하여 주문상태 출력하기
# IF() 이용
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") AS OUT_DATE, 
       IF(OUT_DATE<='2022-05-01', '출고완료', IF(OUT_DATE>'2022-05-01', '출고대기', '출고미정')) AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID;

# CASE문 이용
SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") AS OUT_DATE, 
       CASE WHEN OUT_DATE<='2022-05-01' THEN '출고완료'
            WHEN OUT_DATE IS NULL THEN '출고미정'
            ELSE '출고대기'
       END AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID;

